---
title: "draft genetics visualizations"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
  chunk_output_type: console
---

```{r, include = F}
library(DBI)
library(tidyverse)
library(leaflet)
library(dplyr)
library(sf)
#library(gridExtra)
library(patchwork)

colors_full <-  c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089", #Royal 2
                  "#899DA4", "#C93312", "#DC863B", # royal 1 (- 3)
                  "#F1BB7B", "#FD6467", "#5B1A18", # Grand Budapest 1 (-4)
                  "#D8B70A", "#02401B", "#A2A475", # Cavalcanti 1
                  "#E6A0C4", "#C6CDF7", "#D8A499", "#7294D4", #Grand Budapest 2
                  "#9986A5", "#EAD3BF", "#AA9486", "#B6854D", "#798E87" # Isle of dogs 2 altered slightly
)


tol_muted <- c("#2E2585", "#337538", "#5DA899", "#94CBEC","#DCCD7D", "#C26A77", "#9F4A96","#7E2954")

four_colors <- c("#2E2585","#337538","#C26A77","#7E2954")

grand_budapest <- c("#E6A0C4", "#C6CDF7", "#D8A499", "#7294D4")

moonrise_2 <- c("#798E87FF", "#C27D38FF", "#CCC591FF", "#29211FFF")

a_palette <- c("#2A363BFF", "#019875FF", "#99B898FF", "#FECEA8FF", "#FF847CFF", "#E84A5FFF", "#C0392BFF", "#96281BFF")
pony_o <- c("#4C413FFF", "#5A6F80FF", "#278B9AFF", "#E75B64FF", "#DE7862FF", "#D8AF39FF", "#E8C4A2FF")


library(wesanderson)
?wesanderson::wes_palette()
displayAllColors(wes_palette("Moonrise2"))
# library(colorspace)
# library(scales)
# show_col(tritan(colors_full, severity = 0.6))

library(colorBlindness)
#displayAllColors(torres)
con <- DBI::dbConnect(drv = RPostgres::Postgres(),
                      host = "run-id-database.postgres.database.azure.com",
                      dbname = "runiddb-prod",
                      user = Sys.getenv("runid_db_user"),
                      password = Sys.getenv("runid_db_password"),
                      port = 5432)

DBI::dbListTables(con)

# Emanuel provided this query (https://github.com/SRJPE/jpe-genetics-edi/blob/main/data-query.sql)
run_designation_raw <- dbGetQuery(
  con,
  "SELECT DISTINCT ON (gri.sample_id)
    gri.sample_id,
    rt.run_name,
    substring(gri.sample_id FROM '^[^_]+_((?:100|[1-9][0-9]?))_') AS sample_event,
    st.datetime_collected,
    st.fork_length_mm,
    st.field_run_type_id
FROM
    genetic_run_identification gri
JOIN run_type rt
ON rt.id = gri.run_type_id
JOIN sample st
ON st.id = gri.sample_id
WHERE gri.sample_id LIKE '___24%%'
ORDER BY
    gri.sample_id,
    gri.created_at DESC;
"
)

sample_location <- dbGetQuery(con, "select code, location_name, stream_name, description from sample_location")
sample <- dbGetQuery(con, "select * from sample")

run_designation <- run_designation_raw |> 
  mutate(code = substr(sample_id, 1, 3),
         year= paste0(20,substr(sample_id, 4,5)),
         sample_event = as.numeric(sample_event)) |> 
  left_join(select(sample_location, code, location_name)) 

run_designation_percent <- run_designation |> 
  group_by(location_name, sample_event, year, run_name) |> 
  summarize(count = n()) |> 
  group_by(location_name, year, sample_event) |> 
  mutate(total_sample = sum(count),
         run_percent = (count/total_sample) * 100)
```

# Draft visualizations

- Ask Emanuel about the datetime
- What about data pre 2024?
- Confirm the run labels with Sean

## One year or time series 

```{r}
# Consider option of viewing as percent or as the sample number

#TODO: work on the color scheme, update sample event to a date range (datetime from db is empty so need to figure out how to get that - consult with emanuel), consider making the plot by sample count side-by-side instead of stacked but need to make the width uniform

## Butte Creek - percent
plot1 <- run_designation_percent |> 
  filter(location_name == "Butte", year == 2024) |> 
  ggplot(aes(x = sample_event, y = run_percent, fill = run_name)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_viridis_d(option = "D") +
  scale_y_continuous(breaks = seq(0, 100, by = 20)) + 
  guides(fill = "none") +
  theme_minimal() +
  labs(fill = "",
       x = "",
       y = "Percent")

## Butte Creek - sample number
# run_designation_percent |> 
#   filter(location_name == "Butte", year == 2024) |> 
#   ggplot(aes(x = sample_event, y = count, fill = run_name)) +
#   geom_bar(stat = "identity", position = "stack") +
#   scale_fill_viridis_d(option = "D") +
#   theme_minimal() +
#   labs(fill = "",
#        x = "Sample Event",
#        y = "Sample Count")

## Butte Creek - sample number / side-by-side
plot2 <- run_designation_percent |> 
  filter(location_name == "Butte", year == 2024) |> 
  ggplot(aes(x = sample_event, y = count, fill = run_name)) +
  geom_bar(stat = "identity", 
           position = position_dodge2(width = 0.8, preserve = "single"),  
           width = 0.7) +
  scale_fill_viridis_d(option = "D") +  
  scale_x_continuous(breaks = 1:20) +
  scale_y_continuous(breaks = 1:11) +
  theme_minimal() +
   guides(fill = "none") +
  labs(fill = "",
       x = "Sample Event",
       y = "Sample Count")

plot3 <- run_designation_percent |> 
  filter(location_name == "Butte", year == 2024) |> 
  ggplot(aes(x = sample_event, y = count, color = run_name)) +
  geom_line()+
  scale_color_viridis_d(option = "D") +  
  scale_x_continuous(breaks = 1:20) +
  scale_y_continuous(breaks = 1:11) +
  theme_minimal() +
   guides(color = "none") +
  labs(fill = "",
       x = "Sample Event",
       y = "Sample Count")

#grid.arrange(plot1, plot3, nrow = 2)
# uses patchwork
plot1 / plot3
```

## Aggregated by event/date across multiple years

```{r}
# the idea of this plot is retain the variability based on time of year but aggregate multiple years together
# note that depending on how the filter options work this may not be worth including

run_designation_mean <- run_designation_percent |> 
  group_by(location_name, sample_event, run_name) |> # maybe creating a month variable is better than grouping by sample event
  summarize(run_percent = mean(run_percent, na.rm = T),
            count = sum(count, na.rm = T)) # could also take the average count but think more informative to sum

## We only have 2024 data so this will look the same
plot1 <- run_designation_mean |> 
  filter(location_name == "Butte") |> 
  ggplot(aes(x = sample_event, y = run_percent, fill = run_name)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_viridis_d(option = "D") +
  scale_y_continuous(breaks = seq(0, 100, by = 20)) + 
  guides(fill = "none") +
  theme_minimal() +
  labs(fill = "",
       x = "",
       y = "Percent")

plot3 <- run_designation_mean |> 
  filter(location_name == "Butte") |> 
  ggplot(aes(x = sample_event, y = count, color = run_name)) +
  geom_line()+
  scale_color_viridis_d(option = "D") +  
  scale_x_continuous(breaks = 1:20) +
  scale_y_continuous(breaks = 1:11) +
  theme_minimal() +
   guides(color = "none") +
  labs(fill = "",
       x = "Sample Event",
       y = "Sample Count")

plot1 / plot3
```

## Aggregated proportions

```{r}
# we could also show the sample size as a plot rather than labels. i thought the labels were informative enough and didn't need a bar chart

mean_proportions <- run_designation_percent |> 
  group_by(location_name, run_name) |> 
  summarize(mean_run_percent = mean(run_percent, na.rm = T),
            run_sd = sd(run_percent, na.rm = T),
            count = sum(count, na.rm = T)) # could also take the average count but think more informative to sum

plot1 <- mean_proportions |> 
  filter(location_name == "Butte") |> 
  ggplot(aes(x = run_name, y = mean_run_percent)) +
  geom_bar(stat = "identity", fill = "#9986A5") +
  geom_errorbar(aes(ymin = mean_run_percent - run_sd, ymax = mean_run_percent + run_sd), width = 0.2, color = "gray") +
  geom_text(aes(label = paste0("n=", count), y = 3), size = 3) +
  theme_minimal() +
  labs(x = "",
       y = "Percent")
plot1
```


# Monitoring map

Insert leaflet map here - use this map as a starting place: https://github.com/SRJPE/jpe-map-shiny

```{r echo=FALSE}
# data from jpe
rst_raw <- readRDS("data-raw/rst_sites.Rds")

rst <- rst_raw |> 
  filter(site %in% c("lcc", "ubc", "mill creek", "deer creek", "okie dam",
                     "tisdale", "knights landing", "hallwood", "herringer riffle")) 

# adding Delta Entry and Lower Feather Rm 17
additional_rst <- readxl::read_xlsx("data-raw/sample_locations_20220830.xlsx") |>
  filter(code %in% c("F17", "DEL")) |> 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) |> 
  mutate(stream = tolower(stream_name),
         site = tolower(location_name),
         watershed_name = stream_name, #TODO assuming there is 1 site on these two, check
         popup = case_when(stream == "feather river" ~ "<p><em>Rotary Screw Trap</em></p><p><strong>Feather River</strong></p><p>Number of Subsites: 1</p>",
                           T ~ "<p><em>Rotary Screw Trap</em></p><p><strong>Sacramento River</strong></p><p>Number of Subsites: 1</p>")) |> 
  select(stream, site, geometry, popup, watershed_name, stream_name) 

rst_sites <- bind_rows(additional_rst, rst) 

# habitat extents
salmonid_habitat_extents <- readRDS("data-raw/salmonid_habitat_extents.Rds")

leaflet() |>
  addMapPane("Lines-Habitat", zIndex = 430) |>
  addTiles(urlTemplate = "https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/tile/{z}/{y}/{x}",
           attribution = 'Basemap © Esri, GEBCO, NOAA, CHS, etc.') |>
  addPolylines(data = salmonid_habitat_extents,
               label = ~lapply(river, htmltools::HTML),
               popup = ~river,
               color = "#5299D9",
               opacity = 1,
               weight = 1.5) |> 
  addCircleMarkers(data = rst_sites,
                   radius = 6,
                   fillColor = "black",
                   color = "black",
                   weight = 1,
                   fillOpacity = 0.7,
                   popup = ~popup)

```

