library(shiny)
library(tidyverse)
library(shinythemes)
library(DT)
library(shinyWidgets)
library(lubridate)
library(plotly)
library(shinycssloaders)
library(waterYearType)
# remotes::install_github("cvpia-osc/DSMhabitat")
library(DSMhabitat)
library(ggplot2)
library(mapdata)
library(ggrepel)
library(bayesplot)
# remotes::install_github("SRJPE/SRJPEmodel@wip", force = TRUE)
# remotes::install_github("SRJPE/SRJPEdata")
# library(SRJPEmodel)
